import React from "react";

const ItineraryDisplay = ({ itinerary }) => {
  if (!itinerary) return null;

  // Support either { itinerary: {...} } or just {...}
  const data = itinerary?.itinerary ?? itinerary;
  if (!data) return null;

  const days = Array.isArray(data.days) ? data.days : [];
  const duration = data.duration ?? days.length ?? 0;
  const budget =
    data.budget_breakdown ?? data.budgetBreakdown ?? null;

  return (
    <div className="max-w-5xl mx-auto bg-white p-8 rounded-3xl shadow-lg mt-8 text-gray-800">
      <a href="/planner" className="text-blue-500 hover:underline">
        Edit your trip details
      </a>
      {/* HEADER */}
      <div className="text-center mb-10">
        <h1 className="text-4xl font-bold text-blue-700">
          {data.destination}: {duration}-Day Itinerary
        </h1>
        <p className="text-gray-500 mt-2">
          A curated experience blending adventure, culture, and relaxation.
        </p>
      </div>

      {/* GENERAL INFO */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-10">
        <div className="bg-blue-50 p-4 rounded-xl">
          <h3 className="font-semibold text-blue-700 mb-2">🌤 Estimated Weather</h3>
          <p>Mild & pleasant; best for sightseeing and outdoor exploration.</p>
        </div>
        <div className="bg-blue-50 p-4 rounded-xl">
          <h3 className="font-semibold text-blue-700 mb-2">🧳 Recommended Clothing</h3>
          <p>Light cotton wear, comfortable shoes, hat, and sunscreen.</p>
        </div>
      </div>

      {/* DAILY ITINERARY */}
      <div>
        <h2 className="text-2xl font-semibold text-blue-700 mb-4">
          📅 Daily Itinerary
        </h2>
        {days.map((day, i) => {
          const activities = Array.isArray(day.activities) ? day.activities : [];
          const hiddenGem = day.hidden_gem ?? day.hiddenGem;
          return (
            <div key={day.day ?? i} className="mb-8 border-l-4 border-blue-500 pl-4">
              <h3 className="text-xl font-semibold mb-1">
                Day {day.day ?? i + 1} – {day.title || "Plan"}
              </h3>

              {activities.length > 0 && (
                <ul className="list-disc ml-6 text-gray-700 leading-relaxed mb-2">
                  {activities.map((act, idx) => (
                    <li key={idx}>{act}</li>
                  ))}
                </ul>
              )}

              {hiddenGem && (
                <p className="italic text-gray-500">
                  🌿 Hidden Gem: {hiddenGem}
                </p>
              )}
            </div>
          );
        })}
      </div>

      {/* BUDGET BREAKDOWN */}
      {budget && (
        <div className="mt-10 bg-gray-50 p-6 rounded-2xl shadow-inner">
          <h2 className="text-2xl font-semibold text-blue-700 mb-4">
            💰 Estimated Budget
          </h2>
          {Object.entries(budget).map(([key, value]) => (
            <p key={key} className="capitalize text-gray-700">
              <strong>{key.replace(/_/g, " ")}:</strong> {value}
            </p>
          ))}
        </div>
      )}

      {/* FOOTNOTE */}
      <div className="mt-10 text-center text-gray-500 text-sm">
        <p>Plan generated by Tiragu AI Trip Planner ✨</p>
        <p className="italic">“Travel smart. Travel inspired.”</p>
      </div>
    </div>
  );
};

export default ItineraryDisplay;